### ISSUE TITLE
Test for #12

### ISSUE THREAD

**Issue by kamicut** [AmericanRedCross/osm-stats-workers#13]
It's a rare case but we should cover it with a test.

**Comment by kamicut** [comment]
From @matthewhanson possible test case: http://www.openstreetmap.org/way/394483013/history

**Comment by matthewhanson** [comment]
For reference, here's the link PR12  https://github.com/AmericanRedCross/osm-stats-workers/pull/12 

It could still use a test.  It's different from PR #13, which isn't really valid anymore, see issue #17 and #20

**Comment by matthewhanson** [comment]
Doesn't really apply anymore, geometry calculations different now.
