### ISSUE TITLE
"Pool is destroyed" errors stalling lambda processing

### ISSUE THREAD

**Issue by kriscarle** [AmericanRedCross/osm-stats-workers#26]
The worker runs for a bit, then starts failing with a "pool is destroyed" error. From my searching It seems like that error can occur if the pool is not being destroyed on previous runs of the worker and is filling up all the postgres connections slots. It eventually starts working again, for awhile, possibly when postgres times out and kills the connections.

I see commented out code to manually call knex.destroy() was that an attempt at fixing this issue?  https://github.com/AmericanRedCross/osm-stats-workers/blob/develop/examples/kinesis-consumer/index.js#L26

**Comment by kriscarle** [comment]
Just realized that you already have an issue for this at https://github.com/AmericanRedCross/osm-stats/issues/25

**Comment by matthewhanson** [comment]
That message could be multiple things, knex reports 'pool is destroyed' for pretty much any database error, from an invalid connection string to a host timing out.   However, if it is running for a while it's like due to the same issue which we've been seeing and now finally have verified a fix for (will be in develop branch shortly). In the knex pool parameters set 'min' equal to 0 rather than 1, this will allow the database connection to drop to 0 rather then forcing it to keep a connection alive.

**Comment by kriscarle** [comment]
awesome thanks!

**Comment by kriscarle** [comment]
Unfortunately I started getting this again even with the pool min set to 0

**Comment by matthewhanson** [comment]
Hi Kris, sorry to hear that.    I've been running this steadily in real-time and haven't had any issues for a while now.   Can you give me any more info as to how you are using it?

As I said earlier, the pool is destroyed error can arise from all sorts of reasons and just means there's some sort of database error.   The latest develop branch, if you are using it, does have some db migrations that would have to be run if you are using the latest but created the database with the previous version.

**Comment by kriscarle** [comment]
Hi Matt,

It runs fine for awhile and then basically gets stuck on this error. If I make an unimportant change to generate a zip with a new timestamp via Travis, then run the osmstats.py update, it will starting working again for awhile. Last night it ran for 7 hours.

I'm looking into what I might have setup differently. I'm running on all hash tags so the invocation count is probably much higher. That could be pushing it over a threshold somehow? 

I did merge the latest dev branch, but the migrations ran fine.  At some point I switched the Lambda config to Node 4.3 to see if that made a difference.  I'll try switching it back for awhile. Switching the node version also gets it running again, probably because it is rebuilding/restarting the container.

I'm thinking it may be related to this: https://github.com/tgriesser/knex/issues/1382 I'm going to try updating to knex 11.4+ to see if helps.

Here is the full log with DEBUG=* 
```
Fri, 10 Jun 2016 08:26:43 GMT knex:tx trx1: Starting top level transaction 
Fri, 10 Jun 2016 08:26:43 GMT pool2 New ResourceRequest (id=0, timeout=Infinity) 
Fri, 10 Jun 2016 08:26:43 GMT pool2 Growing pool: no resource to serve request (p=1, tba=0, tbt=0, max=25) 
Fri, 10 Jun 2016 08:26:43 GMT pool2 Attempting to acquire resource (cur=0, ac=0) 
Fri, 10 Jun 2016 08:26:52 GMT pool2 reap (cur=0, av=0) 
Fri, 10 Jun 2016 08:26:52 GMT pool2 Not growing pool: pending=1, to be available=1 
Fri, 10 Jun 2016 08:27:02 GMT pool2 reap (cur=0, av=0) 
Fri, 10 Jun 2016 08:27:02 GMT pool2 Not growing pool: pending=1, to be available=1 
Fri, 10 Jun 2016 08:27:12 GMT pool2 reap (cur=0, av=0) 
Fri, 10 Jun 2016 08:27:12 GMT pool2 Not growing pool: pending=1, to be available=1 
Fri, 10 Jun 2016 08:27:13 GMT pool2 Timed out acquiring resource 
Fri, 10 Jun 2016 08:27:13 GMT pool2 Couldn't allocate new resource: Timed out acquiring resource 
Fri, 10 Jun 2016 08:27:13 GMT pool2 Destroying pool: unable to aquire a resource within 0s 
Fri, 10 Jun 2016 08:27:13 GMT pool2 ResourceRequest: reject (id=0) 
Fri, 10 Jun 2016 08:27:13 GMT pool2 ResourceRequest: fulfilling with error: Pool was destroyed (id=0) 
2016-06-10T08:27:13.322Z	18113039-ebdb-49f2-b245-62e23a6d032a	Knex:warning - Pool2 - Error: Pool was destroyed 
Fri, 10 Jun 2016 08:27:13 GMT pool2 ResourceRequest: clearing timeout (id=0) 
2016-06-10T08:27:13.324Z	18113039-ebdb-49f2-b245-62e23a6d032a	Knex:Error Pool2 - Error: Timed out acquiring resource 
2016-06-10T08:27:13.327Z	18113039-ebdb-49f2-b245-62e23a6d032a	[Error: Pool was destroyed] 
2016-06-10T08:27:13.335Z	18113039-ebdb-49f2-b245-62e23a6d032a	FAILURE: [Error: Pool was destroyed]
```

![image](https://cloud.githubusercontent.com/assets/2431570/15972503/da3b9388-2f0c-11e6-9b4b-ec18543771f2.png)

**Comment by matthewhanson** [comment]
Hi @kriscarle 

I've been running also with all hashtags, and without issue so I've not replicated this issue.   Have you tried increasing the maximum # pool count?

Please let me know if you find anything else out or solve your problem.  I did struggle with pool errors for a while, but at this point it's all working, but I'm very interested in seeing any similar problems.

**Comment by kriscarle** [comment]
Hi @matthewhanson 

That's odd then. There must be something different in our deployments. I wonder if it is a network config issue in AWS. I also commented out the metrics that talk to the OSM API and TM API because outbound connections fail for me. I don't really need those metrics so I figured I'd get back to that. It could mean that I have something different in the way AWS is setup?

 I'm still getting the error, knex 11.5 didn't help. I can try increasing the pool. I'm also looking into catching the exception and then manually rebuilding the connection with a new instance of bookself/knex.

**Comment by matthewhanson** [comment]
@kriscarle Ah, I think I know what might be a problem anyway.  The osm-stats deployment creates security groups for RDS and lambda, and puts the lambda inside the VPC.  However when you do that the lambda function can no longer hit any other URL.   And there might be something going on with the connection related to this.

Take your lambda function out of your VPC, then open up the RDS database for all access.   Then re-enable the OSM API and TM API (just to ensure that's not causing some other error), and test that.   This is how we are running it for missingmaps.

**Comment by kriscarle** [comment]
@matthewhanson I think that fixed it. It has been running for 24hrs now without an error. The VPC subnets must be the problem somehow.

**Comment by matthewhanson** [comment]
Excellent, glad to hear it.  Can you go ahead and close this when you feel comfortable it's resolved?

This feeds into the issue with security groups, which I guess should be another issue.

**Comment by kriscarle** [comment]
Okay, it has been running fine for several days now.
