### ISSUE TITLE
local dev?

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/osm-stats-workers#28]
I want to get my local environment up and running to be able to test new workers and badges.

I followed the readme but its failing on the `knex migrate:latest` step.

```
Working directory changed to ~/git/osm-stats-workers/src/db
Using environment: development
Knex:warning - Pool2 - Error: Pool was destroyed
Knex:Error Pool2 - Error: connect ECONNREFUSED
Error: Pool was destroyed
```

cc @matthewhanson

**Comment by matthewhanson** [comment]
Seems like maybe you don't have a DATABASE_URL environment variable set (and this should be updated in the readme).   Use export to set the db url:

export DATABASE_URL='postgres://uname:pw@hostname:port/dbname'
