### ISSUE TITLE
error processing relations

### ISSUE THREAD

**Issue by matthewhanson** [AmericanRedCross/osm-stats-workers#4]
Some of the errors from the mapathon are due to workers trying to process relations, it tries to convert the nodes to features but fails because it's a relation. 

See this changeset as an example:
http://www.openstreetmap.org/changeset/36871457

One of the huts polygons has a relation to a way.  @kamicut thought it might have been a mistake, but it raises the issue of what to do.

It seems most sensible to simply filter out all relations and not process them at this time.

**Comment by kamicut** [comment]
Relations are important for multipolygon buildings but not a core feature, @smit1678 should we tag this issue as 'future' ?

**Comment by smit1678** [comment]
@kamicut @matthewhanson Seems right. I don't think this will be common. I think we could tag that for the future. That changeset also looks like an error. Not common usage to do an line outline of a building and then related it to a building feature.

**Comment by dalekunce** [comment]
happy with this is a future feature.
