### ISSUE TITLE
PSQL error on `make db/all w/ DATABASE_URL`

### ISSUE THREAD

**Issue by rgwozdz** [AmericanRedCross/osm-stats-workers#42]
Upon executing: `make db/all w/ DATABASE_URL` I am receiving this:

```
psql:sql/raw_countries.sql:319: ERROR:  missing data for column "code"
CONTEXT:  COPY raw_countries, line 232: "233	Aruba ABW"
Makefile:22: recipe for target 'db/raw_countries' failed
make: *** [db/raw_countries] Error 3
```
I tried deleting the white-space between "Aruba" and "ABW", then replaced with a tab, but git indicates no change from original code.

**Comment by mojodna** [comment]
Probably editor-specific; I had the same problem in Atom when I originally added the country names. `^V<tab>` in vim definitely inserts a literal tab (just pushed a change with this).

Give it another shot?
