### ISSUE TITLE
workers handling split-up changesets

### ISSUE THREAD

**Issue by matthewhanson** [AmericanRedCross/osm-stats-workers#7]
Currently, the workers code throws an error if the changeset exists already.

The problem is that changesets can actually be split up in the OSM-planet diff files.   Thus a changeset may appear twice, the metadata will be the same but the edits will be split up across the two records.

Additionally, to support planet-stream dividing up changesets (this will help us keep a low timeout on the lambda function by putting a cap on total number of edits in a changeset the workers will operate on), the workers code needs to be updated to handle split up changesets.

Working on PR for this now.

**Comment by kamicut** [comment]
Fixed
