### ISSUE TITLE
changesets with no tracked changes

### ISSUE THREAD

**Issue by matthewhanson** [AmericanRedCross/osm-stats-workers#9]
Some changesets may not have any valid changes once filtered (non-relations, waterway, highway building, amenity), and thus the buffer and metrics are null.

This looks to occur a significant amount, although I'm not sure if it tends to be solely due to mistakes.

See this changeset
http://www.openstreetmap.org/changeset/36867529

If you look at the history of the way entity, you'll see 36867529 was the first changeset and the only tag was 'area=yes'.   This was edited in changeset 36867642 to be 'building=yes' instead.   Therefore the first changeset doesn't contain any changes that the workers are tracking.

The quickest and easiest method to take care of this is to check that the metrics object is defined before adding to the database.   The worker can then complete successfully rather throwing an error.  However, errors will still be thrown inside the code as it tries to operate on undefined objects.

The better way to do it is to reorder logic to first filter the elements, then proceed with calculating metrics and the buffer if there are any changes remaining.

**Comment by kamicut** [comment]
@matthewhanson makes sense. We can implement a blocking `isValid` before calculateMetrics that has the filterable logic such as https://github.com/AmericanRedCross/osm-stats-workers/issues/4 as well as
```
has a building || has a waterway || has a road || has an amenity
```
